package platform

// Code generated by TestAggregateSpeedResults at 2026-06-17 18:35:15; 
// 该文件通过聚合 test_output/speed_results*.csv 生成，用于提供额外精选测速 URL。

var fastSpeedTestURLs = []string{
        "https://hkg.download.datapacket.com/1000mb.bin", // avg: 2668.24 KB/s, samples: 3, errors: 0
        "https://awscli.amazonaws.com/AWSCLIV2.msi", // avg: 2290.85 KB/s, samples: 3, errors: 0
        "https://dl.google.com/chrome/install/ChromeStandaloneSetup64.exe", // avg: 2266.21 KB/s, samples: 3, errors: 0
        "https://get.enterprisedb.com/postgresql/postgresql-16.3-1-windows-x64.exe", // avg: 2170.72 KB/s, samples: 3, errors: 0
        "https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-8.15.0-linux-x86_64.tar.gz", // avg: 1826.51 KB/s, samples: 2, errors: 1
        "https://ash.download.datapacket.com/1000mb.bin", // avg: 1811.50 KB/s, samples: 3, errors: 0
        "https://developer.download.nvidia.com/compute/cuda/12.5.1/local_installers/cuda_12.5.1_555.42.06_linux.run", // avg: 1782.81 KB/s, samples: 3, errors: 0
        "https://tyo.download.datapacket.com/1000mb.bin", // avg: 1765.16 KB/s, samples: 3, errors: 0
        "https://hnd-jp-ping.vultr.com/vultr.com.1000MB.bin", // avg: 1740.09 KB/s, samples: 2, errors: 1
        "https://sgp.download.datapacket.com/1000mb.bin", // avg: 1711.00 KB/s, samples: 3, errors: 0
        "https://cachefly.cachefly.net/300mb.test", // avg: 1674.64 KB/s, samples: 3, errors: 0
        "https://fra-de-ping.vultr.com/vultr.com.1000MB.bin", // avg: 1627.53 KB/s, samples: 3, errors: 0
        "https://nodejs.org/dist/v22.13.1/node-v22.13.1-x64.msi", // avg: 1535.10 KB/s, samples: 2, errors: 1
        "https://hil.proof.ovh.us/files/1Gb.dat", // avg: 1516.64 KB/s, samples: 3, errors: 0
        "https://developer.download.nvidia.com/compute/cuda/12.5.1/local_installers/cuda_12.5.1_555.85_windows.exe", // avg: 1453.63 KB/s, samples: 3, errors: 0
        "https://ash-speed.hetzner.com/1GB.bin", // avg: 1447.66 KB/s, samples: 3, errors: 0
        "https://sgp.proof.ovh.net/files/1Gb.dat", // avg: 1415.36 KB/s, samples: 3, errors: 0
        "https://updates.cdn-apple.com/2025FallFCS/fullrestores/089-12066/4F86CB11-E6FA-47CB-96A8-527A4CBD9273/iPhone18,3_26.1_23B85_Restore.ipsw", // avg: 1354.33 KB/s, samples: 2, errors: 1
        "https://download.gimp.org/mirror/pub/gimp/v3.0/windows/gimp-3.0.0-setup.exe", // avg: 1317.69 KB/s, samples: 3, errors: 0
        "https://par.download.datapacket.com/1000mb.bin", // avg: 1239.14 KB/s, samples: 3, errors: 0
        "https://lax-ca-us-ping.vultr.com/vultr.com.1000MB.bin", // avg: 1236.75 KB/s, samples: 3, errors: 0
        "https://lax.download.datapacket.com/1000mb.bin", // avg: 1179.38 KB/s, samples: 3, errors: 0
        "https://sgp-ping.vultr.com/vultr.com.1000MB.bin", // avg: 1117.56 KB/s, samples: 2, errors: 1
        "https://static.rust-lang.org/dist/rust-1.83.0-x86_64-unknown-linux-gnu.tar.gz", // avg: 1067.52 KB/s, samples: 3, errors: 0
}
